<?php

namespace Tests\Feature;

use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

/**
 * @property mixed user
 */
class AdminNavigationTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();
    }

    public function testHome()
    {
        $response = $this->actingAs($this->user)->get('/admin');
        $response->assertStatus(200);
    }

    public function testVehicles()
    {
        $response = $this->actingAs($this->user)->get('/admin/vehicles');
        $response->assertStatus(200);
    }

    public function testReservations()
    {
        $response = $this->actingAs($this->user)->get('/admin/reservations');
        $response->assertStatus(200);
    }

    public function testHires()
    {
        $response = $this->actingAs($this->user)->get('/admin/hires');
        $response->assertStatus(200);
    }

    public function testVehicleRates()
    {
        $response = $this->actingAs($this->user)->get('/admin/vehicles/rates');
        $response->assertStatus(200);
    }
}
